### ISSUE TITLE
Problème pending 

### ISSUE THREAD

**Issue by simonbeguin** [simonbeguin/topoguide-simon-beguin#2]
Bonjour, j'ai un problème lors de l'enregistrement de mon application.
Voici le message 

Deployment log
-------------------------------------------------
 > find . -name settings.py
./topoguide/topoguide/settings.py
-------------------------------------------------
 > git restore /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/topoguide/topoguide/settings.py
-------------------------------------------------
 > git fetch origin
-------------------------------------------------
 > git switch main
Your branch is up to date with 'origin/main'.
Already on 'main'
-------------------------------------------------
 > git pull origin main --ff-only
Already up to date.
From github.com:simonbeguin/topoguide-simon-beguin
 * branch            main       -> FETCH_HEAD
-------------------------------------------------
 > git rev-parse HEAD
8a5c1cc4db9c73cb1b3de9f8e446910394f49a93
-------------------------------------------------
 > /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/bin/pip install django
Requirement already satisfied: django in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (4.0.4)
Requirement already satisfied: asgiref<4,>=3.4.1 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django) (3.5.0)
Requirement already satisfied: backports.zoneinfo in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django) (0.2.1)
Requirement already satisfied: sqlparse>=0.2.2 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django) (0.4.2)
-------------------------------------------------
 > /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/bin/pip install django
Requirement already satisfied: django in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (4.0.4)
Requirement already satisfied: sqlparse>=0.2.2 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django) (0.4.2)
Requirement already satisfied: asgiref<4,>=3.4.1 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django) (3.5.0)
Requirement already satisfied: backports.zoneinfo in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django) (0.2.1)
-------------------------------------------------
 > /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/bin/pip install  django-bootstrap-v5
Requirement already satisfied: django-bootstrap-v5 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (1.0.11)
Requirement already satisfied: beautifulsoup4<5.0.0,>=4.8.0 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django-bootstrap-v5) (4.11.1)
Requirement already satisfied: django<5.0,>=2.2 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django-bootstrap-v5) (4.0.4)
Requirement already satisfied: soupsieve>1.2 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from beautifulsoup4<5.0.0,>=4.8.0->django-bootstrap-v5) (2.3.2.post1)
Requirement already satisfied: backports.zoneinfo in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django<5.0,>=2.2->django-bootstrap-v5) (0.2.1)
Requirement already satisfied: asgiref<4,>=3.4.1 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django<5.0,>=2.2->django-bootstrap-v5) (3.5.0)
Requirement already satisfied: sqlparse>=0.2.2 in /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages (from django<5.0,>=2.2->django-bootstrap-v5) (0.4.2)
-------------------------------------------------
 > /opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/bin/python manage.py migrate
Traceback (most recent call last):
  File "manage.py", line 22, in <module>
    main()
  File "manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages/django/core/management/__init__.py", line 420, in execute
    django.setup()
  File "/opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages/django/__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "/opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages/django/apps/registry.py", line 116, in populate
    app_config.import_models()
  File "/opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/venv/lib/python3.8/site-packages/django/apps/config.py", line 304, in import_models
    self.models_module = import_module(models_module_name)
  File "/usr/local/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/opt/awng/integration/simonbeguin/topoguide-simon-beguin/main/topoguide/itineraires/models.py", line 1, in <module>
    from tkinter import CASCADE
  File "/usr/local/lib/python3.8/tkinter/__init__.py", line 36, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
ModuleNotFoundError: No module named '_tkinter'

**Comment by trsalomon** [comment]
Le problème vient de la première ligne de ton fichier models.py :
`from tkinter import CASCADE`
The [tkinter](https://docs.python.org/fr/3/library/tkinter.html#module-tkinter) package ("Tk interface") is the standard Python interface to the Tcl/Tk GUI toolkit.
Ça sert à développer des interfaces graphiques pour client lourd, ça ne fonctionne pas pour des applis web.
Le serveur de déploiement ne contient pas de console graphique et ne supporte pas cette extension.
Tu n'en as pas besoin, il faut que tu retires cet import.
